//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmeal_fees
    {
        public int meal_fee_id { get; set; }
        public string meal { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<float> disc_price { get; set; }
        public Nullable<System.DateTime> meal_update { get; set; }
    }
}
