//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsamportallog
    {
        public int LogId { get; set; }
        public string Event { get; set; }
        public string Description { get; set; }
        public string User { get; set; }
        public System.DateTime Timestamp { get; set; }
    }
}
