//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class culinarytraineeinfo_copy
    {
        public int AppNo { get; set; }
        public string MNNo { get; set; }
        public Nullable<System.DateTime> DateApplied { get; set; }
        public string Rank { get; set; }
        public System.DateTime Bdate { get; set; }
        public string Lname { get; set; }
        public string Fname { get; set; }
        public string Mname { get; set; }
        public string Comment { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Weight { get; set; }
        public string ContactNo { get; set; }
        public string Schoolgrad { get; set; }
        public Nullable<short> Yeargrad { get; set; }
        public Nullable<int> SeaServ { get; set; }
        public string TesdaCOC { get; set; }
        public Nullable<double> BMI { get; set; }
        public Nullable<double> SETSEnglish { get; set; }
        public string WorkExperiences { get; set; }
        public string EducationalBackground { get; set; }
        public string Comprehension { get; set; }
        public string CookingAbility { get; set; }
        public string BakingAbility { get; set; }
        public string Personality { get; set; }
        public string Observation { get; set; }
        public string FinalRemarks { get; set; }
        public string Interviewer { get; set; }
        public string Stat { get; set; }
        public string RemarksPOT { get; set; }
        public string RemarksPER { get; set; }
        public string RemarksMOT { get; set; }
        public string RemarksCOM { get; set; }
        public Nullable<int> ScorePOT { get; set; }
        public Nullable<int> ScorePER { get; set; }
        public Nullable<int> ScoreMOT { get; set; }
        public Nullable<int> ScoreCOM { get; set; }
        public string CourseTaken { get; set; }
        public string PositionApplied { get; set; }
        public string Birthplace { get; set; }
        public string TrainingsAttended { get; set; }
        public string Recommendation { get; set; }
    }
}
