//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class esdi_vtblcbtrecords
    {
        public int Id { get; set; }
        public string uCBTResultID { get; set; }
        public string uOBLModuleID { get; set; }
        public Nullable<int> iOBLModuleID { get; set; }
        public string vUserId { get; set; }
        public string vCD { get; set; }
        public string vModuleName { get; set; }
        public string uParentOBLModuleID { get; set; }
        public Nullable<System.DateTime> dtDate { get; set; }
        public Nullable<double> vTime { get; set; }
        public string tiTotalScore { get; set; }
        public string tiTotalCompleted { get; set; }
        public Nullable<int> iInstallationID { get; set; }
        public string vInstallationName { get; set; }
    }
}
