//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbehavioral_assessment
    {
        public long bapt_id { get; set; }
        public string bapt_mnno { get; set; }
        public Nullable<int> bapt_schedid { get; set; }
        public Nullable<int> gen_conduct { get; set; }
        public Nullable<int> bapt_comm { get; set; }
        public Nullable<int> bapt_init { get; set; }
        public Nullable<int> bapt_assert { get; set; }
        public string bapt_comment { get; set; }
        public Nullable<int> bapt_encoder { get; set; }
        public Nullable<System.DateTime> bapt_datecoded { get; set; }
        public string bapt_batci_remark { get; set; }
    }
}
