//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_individual_remarks
    {
        public long bir_id { get; set; }
        public string bir_mnno { get; set; }
        public Nullable<int> bir_batchno { get; set; }
        public string bir_remarks { get; set; }
        public Nullable<System.DateTime> bir_dateinserted { get; set; }
        public Nullable<int> bir_insertedby { get; set; }
        public Nullable<System.DateTime> bir_lastupdated { get; set; }
        public Nullable<int> bir_lastupdateby { get; set; }
    }
}
