//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_merits_list
    {
        public int merits_list_id { get; set; }
        public string merits_names { get; set; }
        public string merits_description { get; set; }
        public string active_merits { get; set; }
    }
}
