//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatchassignment
    {
        public string AppNo { get; set; }
        public string BatchName { get; set; }
        public System.DateTime DateAssigned { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string Vessel { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string USVisa { get; set; }
        public Nullable<System.DateTime> Availability { get; set; }
    }
}
