//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbehavioral_asessment_gen_remark
    {
        public long bhvr_gen_rmrk_id { get; set; }
        public string bhvr_gen_mnno { get; set; }
        public string first_block_gen_remark { get; set; }
        public Nullable<int> latest_encoder_a { get; set; }
        public Nullable<System.DateTime> date_last_updated_a { get; set; }
        public string second_block_gen_remark { get; set; }
        public Nullable<int> latest_encoder_b { get; set; }
        public Nullable<System.DateTime> date_last_updated_b { get; set; }
        public string third_block_gen_remark { get; set; }
        public Nullable<int> latest_encoder_c { get; set; }
        public Nullable<System.DateTime> date_last_updated_c { get; set; }
    }
}
