//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcbttraining
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblcbttraining()
        {
            this.tblcbtscheddetails = new HashSet<tblcbtscheddetail>();
        }
    
        public int CBTID { get; set; }
        public string CDNo { get; set; }
        public Nullable<double> Seagull_no { get; set; }
        public string CourseName { get; set; }
        public string RankTakers { get; set; }
        public Nullable<int> branch_open { get; set; }
        public string Version { get; set; }
        public string Provider { get; set; }
        public Nullable<int> category { get; set; }
        public string Introduction { get; set; }
        public string Relevant_Leg_and_Ref { get; set; }
        public string Course_Topics { get; set; }
        public string Target_Group { get; set; }
        public string Prerequisite { get; set; }
        public string Duration { get; set; }
        public string Credits { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public Nullable<int> YearsValid { get; set; }
        public Nullable<int> OpeningMonths { get; set; }
        public string OpenLinks { get; set; }
        public string CBTCode { get; set; }
        public Nullable<int> ExpirationYears { get; set; }
        public Nullable<int> Display_cbt { get; set; }
        public Nullable<int> Active { get; set; }
        public string Seagull_Code { get; set; }
        public Nullable<sbyte> Issued_Cert { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblcbtscheddetail> tblcbtscheddetails { get; set; }
    }
}
