//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcrew_otherinfo
    {
        public string MNNO { get; set; }
        public string homeAddress { get; set; }
        public string contactEmail { get; set; }
        public string License { get; set; }
        public string eContactName { get; set; }
        public string eRelationship { get; set; }
        public string eContactNo { get; set; }
        public string eAddress { get; set; }
    }
}
