//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcrew_trainingbooking_reason
    {
        public long bookingreason_id { get; set; }
        public Nullable<int> SchedID { get; set; }
        public string MNNo { get; set; }
        public Nullable<int> bg_reason_id { get; set; }
        public string bg_remarks { get; set; }
        public Nullable<int> bg_training_id { get; set; }
        public Nullable<int> booker_id { get; set; }
        public string booker_group { get; set; }
        public Nullable<System.DateTime> date_entered { get; set; }
        public string booking_typ { get; set; }
        public string crew_rank { get; set; }
        public string crew_vessel { get; set; }
        public string crew_principal { get; set; }
    }
}
