//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhotel_guest_remark_type
    {
        public int id_h_rmrk { get; set; }
        public string h_rmrk { get; set; }
        public Nullable<int> h_rmrk_order { get; set; }
        public Nullable<int> remark_display_dorm { get; set; }
        public Nullable<int> remark_display_hotel { get; set; }
        public Nullable<int> remark_display_culinary { get; set; }
    }
}
