//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblloghistory
    {
        public long LogNo { get; set; }
        public string User { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Page { get; set; }
        public string LogBook { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> CompanyCode { get; set; }
    }
}
