//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloff_site_reservation
    {
        public long Id { get; set; }
        public string MNNO { get; set; }
        public string Rank { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string HotelName { get; set; }
        public int RoomType { get; set; }
        public string Classification { get; set; }
        public int Status { get; set; }
        public System.DateTime CheckInDate { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public int CompanyId { get; set; }
        public int ModeOfPayment { get; set; }
        public int ReasonOfStay { get; set; }
        public string Remarks { get; set; }
        public int CrewBatch { get; set; }
        public string BookerRemarks { get; set; }
        public string ReservationBy { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public string LastUpdatedBy { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual tblcrew tblcrew { get; set; }
    }
}
