//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrecord_movement
    {
        public long RcrdID { get; set; }
        public string APIOrigin { get; set; }
        public string ActionToUse { get; set; }
        public string RecordID { get; set; }
        public string Acted { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> DateActed { get; set; }
        public string DateInserted { get; set; }
    }
}
