//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblspecialcourserequest
    {
        public int Id { get; set; }
        public string CourseName { get; set; }
        public System.DateTime StartDate { get; set; }
        public int NumberOfParticipants { get; set; }
        public string Notes { get; set; }
        public System.DateTime DateRequested { get; set; }
        public string RequestedBy { get; set; }
        public string Status { get; set; }
        public int CompanyId { get; set; }
    }
}
