//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmeal_log
    {
        public long control_no { get; set; }
        public string emp_no { get; set; }
        public string emp_name { get; set; }
        public Nullable<System.DateTime> meal_date { get; set; }
        public Nullable<System.TimeSpan> meal_time { get; set; }
        public string meal_type { get; set; }
        public string meal_group { get; set; }
        public string department { get; set; }
    }
}
