//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbltrainingclassification
    {
        public int id { get; set; }
        public string Classification { get; set; }
        public string SubClassification { get; set; }
        public string Category { get; set; }
        public string Training_list { get; set; }
        public Nullable<int> Web_order { get; set; }
        public Nullable<int> gen_course_order { get; set; }
        public Nullable<int> cadetship_crse_order { get; set; }
        public Nullable<int> course_design_doc_order { get; set; }
    }
}
