//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbluser
    {
        public int userno { get; set; }
        public string user { get; set; }
        public string pass { get; set; }
        public string web_pass { get; set; }
        public string active_accnt { get; set; }
        public string accessname { get; set; }
        public string u_rank { get; set; }
        public string u_lname { get; set; }
        public string u_fname { get; set; }
        public string randd_access { get; set; }
        public string email { get; set; }
        public string accessmode { get; set; }
        public string oncall { get; set; }
        public Nullable<int> groupID { get; set; }
        public string cdtrecord { get; set; }
        public string batchass { get; set; }
        public string uploadgrades { get; set; }
        public string cdtmonitor { get; set; }
        public string groupreport { get; set; }
        public string batchreport { get; set; }
        public string schoreport { get; set; }
        public string poolreport { get; set; }
        public string adsreport { get; set; }
        public string writtensched { get; set; }
        public string culrecord { get; set; }
        public string crewrecord { get; set; }
        public string culbatch { get; set; }
        public string culmon { get; set; }
        public string createschedule { get; set; }
        public string cbtschedule { get; set; }
        public string viewparticipants { get; set; }
        public string specialtraining { get; set; }
        public string classes { get; set; }
        public string cbttraining { get; set; }
        public string culbatchreport { get; set; }
        public string culmasterlist { get; set; }
        public string matrix_report { get; set; }
        public string matrix_report_high { get; set; }
        public string print_cert { get; set; }
        public string assign_cert { get; set; }
        public string outside_access { get; set; }
        public string outside_access_matrix { get; set; }
        public string dorm_booking { get; set; }
        public string delete_record { get; set; }
        public string hotel_booking { get; set; }
        public string trainee_record { get; set; }
        public string external_record { get; set; }
        public string mnrecord { get; set; }
        public string operation { get; set; }
        public string thirdparty { get; set; }
        public string dormitory { get; set; }
        public string report { get; set; }
        public string marketReport { get; set; }
        public string paymentSummary { get; set; }
        public string dataexchange { get; set; }
        public string reopen_grading { get; set; }
        public string hotel_dorm_reporting { get; set; }
        public string external_booking { get; set; }
        public string cashier { get; set; }
        public string dwnld_cert { get; set; }
        public string mtrx_meal_prov { get; set; }
        public string UserCompany { get; set; }
        public string ViewAttendance { get; set; }
        public string cadet_records { get; set; }
        public string mtrx_cdt_records_v { get; set; }
        public string cadet_course_booking { get; set; }
        public string deck_engine_access { get; set; }
        public Nullable<int> user_class { get; set; }
        public string crew_regrouping { get; set; }
        public string a_directory_full_control { get; set; }
        public string b_qa_full_ctrl { get; set; }
        public string c_courses_full_control { get; set; }
        public string trainees_info_locked { get; set; }
        public string recruitment_booking { get; set; }
        public string sales_mod { get; set; }
        public string training_coordinator { get; set; }
        public string booking_group { get; set; }
        public string audit_trail { get; set; }
        public Nullable<int> company_access { get; set; }
        public string cy_intended_report { get; set; }
        public string emp_id { get; set; }
        public string user_pos { get; set; }
        public string um_booker_group { get; set; }
        public string helpdesk_access { get; set; }
        public string grade_display_access { get; set; }
        public string opn_schedule_creator { get; set; }
        public string opn_schedule_instructor { get; set; }
        public Nullable<int> behavioral_access { get; set; }
    }
}
