//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldorm_fees
    {
        public int dorm_fee_id { get; set; }
        public string accommodation { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<float> disc_price { get; set; }
        public Nullable<System.DateTime> cost_update { get; set; }
        public Nullable<int> accom_type { get; set; }
    }
}
