//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch
    {
        public int batchNo { get; set; }
        public string batchName { get; set; }
        public Nullable<short> batchYear { get; set; }
        public string rank { get; set; }
        public string batchDesc { get; set; }
        public Nullable<System.DateTime> trainingStarted { get; set; }
        public Nullable<System.DateTime> trainingEnded { get; set; }
        public string category { get; set; }
        public string display_batch { get; set; }
        public string @class { get; set; }
        public Nullable<int> curriculum_used { get; set; }
        public Nullable<int> display_to_matrix { get; set; }
        public Nullable<int> ordering_batch { get; set; }
        public Nullable<int> recruitment_use { get; set; }
        public Nullable<int> external_batch { get; set; }
        public Nullable<int> batch_for_cadetship { get; set; }
        public Nullable<int> next_batch_id { get; set; }
        public Nullable<int> opn_display { get; set; }
        public Nullable<int> last_batch_id { get; set; }
        public Nullable<int> merit_starting_points { get; set; }
    }
}
