//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblrank
    {
        public string rank { get; set; }
        public string description { get; set; }
        public string department { get; set; }
        public Nullable<int> rank_level { get; set; }
        public Nullable<int> elect_class { get; set; }
        public string main_rank { get; set; }
    }
}
