//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblschedule_registration_ofcrew
    {
        public int idno { get; set; }
        public Nullable<int> SchedID { get; set; }
        public Nullable<int> TrainingID { get; set; }
        public string mnno { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<float> DollarFeeAmount { get; set; }
        public Nullable<float> PesoFeeAmount { get; set; }
        public Nullable<int> PaymentMode { get; set; }
        public string RecBy { get; set; }
    }
}
