//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_offense_category
    {
        public int cat_offense_id { get; set; }
        public string offense_category { get; set; }
        public Nullable<int> offense_demerit_points { get; set; }
        public Nullable<int> offense_order { get; set; }
    }
}
