//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_general_remarks
    {
        public long bgr_id { get; set; }
        public Nullable<int> bgr_batchno { get; set; }
        public string bgr_general_remarks { get; set; }
        public Nullable<System.DateTime> bgr_dateinserted { get; set; }
        public Nullable<int> bgr_insertedby { get; set; }
        public Nullable<System.DateTime> bgr_lastupdated { get; set; }
        public Nullable<int> bgr_lastupdatedby { get; set; }
    }
}
