//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_offense_records
    {
        public int offense_record_id { get; set; }
        public string or_mnno { get; set; }
        public Nullable<int> or_batchno { get; set; }
        public Nullable<int> or_offense_category { get; set; }
        public Nullable<int> or_offense_id { get; set; }
        public string or_offense_remarks { get; set; }
        public Nullable<int> or_insertedby { get; set; }
        public Nullable<System.DateTime> or_dateinserted { get; set; }
        public Nullable<int> or_updatedby { get; set; }
        public Nullable<System.DateTime> or_dateupdated { get; set; }
    }
}
