//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_individual_merit_points
    {
        public long crew_merits_id { get; set; }
        public Nullable<int> cm_batchno { get; set; }
        public string cm_mnno { get; set; }
        public Nullable<int> cm_merits_id { get; set; }
        public string cm_remarks { get; set; }
        public Nullable<int> cm_points { get; set; }
        public Nullable<int> cm_insertedby { get; set; }
        public Nullable<System.DateTime> cm_dateinserted { get; set; }
        public Nullable<int> cm_updatedby { get; set; }
        public Nullable<System.DateTime> cm_datelastupdated { get; set; }
    }
}
