//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAMPortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblbatch_merits_demerits
    {
        public long batch_merits_id { get; set; }
        public Nullable<int> bm_batchno { get; set; }
        public string bm_type { get; set; }
        public Nullable<int> bm_merits_point { get; set; }
        public string bm_remarks { get; set; }
        public Nullable<int> bm_insertedby { get; set; }
        public Nullable<System.DateTime> bm_dateinserted { get; set; }
        public Nullable<int> bm_updatedby { get; set; }
        public Nullable<System.DateTime> bm_datelastupdated { get; set; }
    }
}
